client/EntriesPage: Fix regression in open action
    TypeError: eD.MouseEvent is not a constructor

I accidentally broke it in 1041a6cae586ae1388734355789b47c2d8536c45.