build: Prepare zipball build for Composer bump
Composer 2.6.4+ wants to have reproducible outputs so it preserves `mtime` when copying files:
https://github.com/composer/composer/pull/11663
This becomes an issue with `vendor/composer/ClassLoader.php`,
which is copied from Nix store so it has `mtime` of 0 (1970-01-01),
because that is not supported by ZIP:

    ValueError: ZIP does not support timestamps before 1980

Let’s disable strict timestamps to clamp the out-of-range timestamps to ZIP epoch.
That argument was actually introduced because of reproducible builds:
https://bugs.python.org/issue34097